version: '3.8'

services:
  service_node:
    image: node:efasdfasd
    build: ./node
    container_name: container_node_efasdfasd
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes:
      - ../:/tmp/work
    networks:
      - container_network
    depends_on:
      - service_postgres

  service_postgres:
    image: postgres:14.15
    container_name: container_postgres_efasdfasd
    environment:
      POSTGRES_USER: ${DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    networks:
      - container_network
    # volumes:
    #   - volume_postgres:/var/lib/postgresql/data

networks:
  container_network:
    external: true
