version: '3.8'

services:
  service_node_efasdfasd:
    image: node:efasdfasd
    build: ./node
    container_name: container_node_efasdfasd
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes:
      - ../:/tmp/work
    networks:
      - container_network
    depends_on:
      - service_postgres_efasdfasd
  
  service_postgres_efasdfasd:
    image: postgres:14.15
    container_name: container_postgres_efasdfasd
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db01
    ports: 
      - "5432:5432"
    networks:
      - container_network
    # volumes:
    #   - volume_postgres:/var/lib/postgresql/data
      
networks:
  container_network:
      external: true
